name: Test Squads V4 Program Upgrade

on: [push, pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest

    env:
      DEPLOYER_KEYPAIR: ${{ secrets.DEPLOYER_KEYPAIR }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List files
        run: ls

      - run: ls /action

      - run: yarn
      - run: yarn build

  test:
    uses: ./action/action.yml@main
    with:
      network-url: "https://api.devnet.solana.com"
      multisig-pda: "Aumm6P4VT4RcZUspSBRRkTYt2RFCWVfUhci23LrFNfZC"
      multisig-vault-index: "1"
      program-id: "example-program-id"
      buffer: "Hs93mJ3HC9qJz6ttpGGk12piv1bVxndv1RE86t585Duj"
      spill-address: "FU2pN8qudMjtBCnU6QAavsvhZFTgXrdJ8JkLRArRuZ4n"
      name: "Test Upgrade"
      keypair: ${{ secrets.DEPLOYER_KEYPAIR }}
